<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Payment</title>
<style>

.razorpay-payment-button{
   display: none;
}
</style>

</head>
<body>

<div style="width:47%;margin-left: 26%;" id="maindiv">
<form action="{{route('artwork.payment.validate')}}" method="POST" class="form-group">
@csrf

<input type="hidden" name="tracking_number" value="{{$receipt}}" >
<script
src="https://checkout.razorpay.com/v1/checkout.js"
 data-key="{{$apiKey}}" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
 data-amount="{{$amount}}" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
 data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
 data-order_id="{{$order_id}}"//Replace with the order_id generated by you in the backend.
 data-buttontext="Proceed to Payments"
 data-name="the Art Hive"
 data-description="Ecommerce Website"
 data-image="https://thearthive.co.in/public/assets/pictures/logoattached.png"
 data-prefill.name="{{$name}}"
 data-prefill.email="{{$email}}"
 data-prefill.contact="{{$mobile}}"
 data-theme.color="#F37254"
 data-notes.shopping_order_id ="{{$receipt}}"
></script>
<input type="hidden" custom="Hidden Element" name="content_type" value="{{$content_type}}">

       

</form>

</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

<script type="text/javascript">
    document.querySelector(".razorpay-payment-button").click();
</script>
</body>
</html>

